=== XiaoJihua/DTD-to-XML-transformeris/Final project/output.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xsd:element name="team">
<xsd:complexType>
<xsd:sequence minOccurs="0" maxOccurs="unbounded">
<xsd:element name="person" minOccurs="1" maxOccurs="1">
<xsd:complexType>
<xsd:sequence minOccurs="1" maxOccurs="1">
<xsd:element name="name" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
<xsd:element name="city" type="xsd:string" minOccurs="0" maxOccurs="1"/>
<xsd:choice minOccurs="1" maxOccurs="1">
<xsd:sequence minOccurs="1" maxOccurs="1">
<xsd:element name="elem1" type="xsd:string" minOccurs="1" maxOccurs="1"/>
<xsd:sequence minOccurs="1" maxOccurs="1">
<xsd:element name="elem2" type="xsd:string" minOccurs="1" maxOccurs="1"/>
<xsd:element name="elem3" type="xsd:string" minOccurs="1" maxOccurs="1"/>
</xsd:sequence>
<xsd:element name="elem4" type="xsd:string" minOccurs="1" maxOccurs="1"/>
</xsd:sequence>
<xsd:sequence minOccurs="1" maxOccurs="1">
<xsd:element name="elem5" type="xsd:string" minOccurs="1" maxOccurs="1"/>
<xsd:element name="elem6" type="xsd:string" minOccurs="1" maxOccurs="1"/>
</xsd:sequence>
</xsd:choice>
<xsd:choice minOccurs="1" maxOccurs="1">
<xsd:element name="elem7" type="xsd:string" minOccurs="1" maxOccurs="1"/>
<xsd:element name="elem8" type="xsd:string" minOccurs="1" maxOccurs="1"/>
</xsd:choice>
<xsd:element name="salary" type="xsd:string" minOccurs="1" maxOccurs="1"/>
</xsd:sequence>
<xsd:attribute name="id" type="xsd:string" use="required"/>
<xsd:attribute name="position" type="xsd:string" use="optional"/>
</xsd:complexType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
<xsd:key name="idKey">
<xsd:selector xpath=".//person"/>
<xsd:field xpath="@id"/>
</xsd:key>
</xsd:element>
</xsd:schema>

=== XiaoJihua/DTD-to-XML-transformeris/Final project/2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<team xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com output.xsd">
<person position="kapitan" id="i1">
<name>
</name>
<city>
</city>
<salary>
</salary>
</person>
<person position="vyvojar" id="i2">
<name>
</name>
<salary>
</salary>
</person>
<person position="vyvojar" id="i3">
<name>
</name>
<salary>
</salary>
</person>
<person position="tester" id="i4">
<name>
</name>
<city>
</city>
<salary>
</salary>
</person>
</team>
