=== XiaoJihua/DTD-to-XML-transformeris/examples/2.dtd
<!ELEMENT team (person)*>
<!ELEMENT person (name, city?, salary)*>
<!ATTLIST person 
         id ID #REQUIRED 
         position CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== XiaoJihua/DTD-to-XML-transformeris/examples/2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE team SYSTEM "2.dtd">

<team>
    <person position="kapitan" id="i1">
		<name>Ivan</name>
		<city>Brno</city>
		<salary>20000</salary>
    </person>

    <person position="vyvojar" id="i2">
        <name>Tomas</name>
		<salary>15000</salary>
    </person>
        
    <person position="vyvojar" id="i3">
        <name>Simon</name>
		<salary>10000</salary>
    </person>
	
	<person position="tester" id="i4">
        <name>Matej</name>
		<city>Brno</city>
		<salary>5000</salary>
    </person>
</team>
